### ISSUE TITLE
(centos6) md5sum expects 2 spaces between checksum and input file

### ISSUE THREAD

**Issue by streetster** [neomantra/docker-onload#1]
Trying to build from a `centos:6.7` base with
```
docker build . -f centos/Dockerfile --build-arg ONLOAD_CENTOS_TAG=6.7
```
errors with:
```
md5sum: standard input: no properly formatted MD5 checksum lines found
```
As per [https://forum.openoffice.org/en/forum/viewtopic.php?f=16&t=83825](here) this is due to md5sum expecting 2 spaces (rather than 1), e.g. line 63 should be:
```
    && echo "${ONLOAD_MD5SUM}  openonload-${ONLOAD_VERSION}.tgz" | md5sum --check \
```

I'll fork and submit a PR if desired.

**Comment by neomantra** [comment]
It looks like Centos 6 and Centos 7 `md5sum` commands both accept the two spaces, so I'll add a space.  

In creating these Dockerfiles, other `md5sum` programs (maybe for older Debian) wanted that formatting.   I made all this MD5 checking because Solarflare provided checksums but didn't protect openonload.org with HTTPS -- now they do.

**Comment by neomantra** [comment]
OK, that's on master.  Thanks again... happy kernel-bypassing!
